prod:
  image: vizzuality/gfw-area:1.1.1${STAGING}
  ports:
    - "4100"
  env_file:
    - prod.env
  command: start
  dns: 
    - ${DNS_SERVER}
    - 8.8.8.8
  restart: always
  log_driver: "syslog"
  log_opt:
      syslog-address: ${SYSLOG_ADDRESS}
      tag: gfw-area${STAGING}
